name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Check if diff should be committed
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@github-actions commit-diff'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Commit diff
        if: steps.check.outputs.triggered == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Commit changed files'
